feat: Break out `globals` directory in maple-core to be a submodule dapptools project (SC-3056)
maple-labs/globals pull request #1
Opened 2021-07-26 08:32 UTC by satyamakgec

2021-07-26 14:54 UTC, deluca-mike requested changes

2021-07-26 14:54 UTC, deluca-mike commented on build.sh
> +mv -f lib/calculator/lib/ds-test/contracts lib/calculator/lib/ds-test/src
We're going to put all submodules in `modules` directory to prevent opinionated dapp from the weird stuff it assumes should be in `lib`.

2021-07-26 14:54 UTC, deluca-mike commented on .gitmodules
> +	url = https://github.com/maple-labs/oracle.git
We're going to put all submodules in `modules` directory to prevent opinionated dapp from the weird stuff it assumes should be in `lib`.

2021-07-26 14:54 UTC, deluca-mike commented on .gitignore
> +.vscode/*
new line at end of file.

2021-07-26 14:54 UTC, deluca-mike commented on config/ci.json
> +}
new line at end of the file

2021-07-26 14:54 UTC, deluca-mike commented on config/dev.json
> +}
new line at the end of the file.

2021-07-26 14:54 UTC, deluca-mike commented on config/prod.json
> +}
new line at the end of the file.

2021-07-26 14:54 UTC, deluca-mike commented on contracts/MapleGlobals.sol
> +import { ISubFactory } from "../lib/subfactory/contracts/interfaces/ISubFactory.sol";
```suggestion
import { ICalc }       from "../modules/calculator/contracts/interfaces/ICalc.sol";
import { IOracle }     from "../modules/oracle/contracts/interfaces/IOracle.sol";
import { ISubFactory } from "../modules/subfactory/contracts/interfaces/ISubFactory.sol";
```

2021-07-26 14:54 UTC, deluca-mike commented on contracts/MapleGlobals.sol
> +import { SafeMath } from "../lib/openzeppelin-contracts/contracts/math/SafeMath.sol";
```suggestion
import { SafeMath } from "../modules/openzeppelin-contracts/contracts/math/SafeMath.sol";
```

2021-07-26 14:54 UTC, deluca-mike commented on contracts/interfaces/IERC20Details.sol
> +}
new line at the end of the file.

2021-07-26 14:54 UTC, deluca-mike commented on contracts/interfaces/IERC20Details.sol
> +import { IERC20 } from "../../lib/openzeppelin-contracts/contracts/token/ERC20/IERC20.sol";
```suggestion
import { IERC20 } from "../../modules/openzeppelin-contracts/contracts/token/ERC20/IERC20.sol";
```

2021-07-26 14:54 UTC, deluca-mike commented on test.sh
> +mv -f lib/calculator/lib/ds-test/contracts lib/calculator/lib/ds-test/src
No longer need a workaround since we're going to use `modules` to not have to deal with `lib` stuff.
Also, new line at the end of the file.

2021-07-26 14:54 UTC, deluca-mike commented on test.sh
> +mv -f lib/calculator/lib/ds-test/src lib/calculator/lib/ds-test/contracts
No longer need a workaround since we're going to use modules to not have to deal with lib stuff.
Also, new line at the end of the file.

2021-07-26 15:52 UTC, lucas-manuel commented
test

2021-07-28 20:50 UTC, lucas-manuel commented
Closing duplicate PR

2021-07-28 20:50 UTC, closed without merging